### ISSUE TITLE
Documentation is not helpful

### ISSUE THREAD

**Issue by JafferWilson** [areski/django-nvd3#100]
Hello @areski 
I was going through the examples and the related documentation of your repository. I could not understand what all parameters I can pass in order to get the effects that I am will to have. For example:
I was visiting the website nvd3.org and like the effect of the line that shows the corresponding values: http://nvd3.org/examples/cumulativeLine.html
I do not understand how I can get it done in the Django-NVD3?
Please will you update your documentation related to the parameters what can be passed through the views.py and will be rendered at the template side?
Please reply.

**Comment by cultivater** [comment]
I have the same question...
The so-called documentation just provided some simple examples, which are less helpful.
BTW, how did you solve your problem? Could you please help me, thank you so much :)

**Comment by cultivater** [comment]
> 
> 
> Hello @areski
> I was going through the examples and the related documentation of your repository. I could not understand what all parameters I can pass in order to get the effects that I am will to have. For example:
> I was visiting the website nvd3.org and like the effect of the line that shows the corresponding values: http://nvd3.org/examples/cumulativeLine.html
> I do not understand how I can get it done in the Django-NVD3?
> Please will you update your documentation related to the parameters what can be passed through the views.py and will be rendered at the template side?
> Please reply.

I have the same question...
The so-called documentation just provided some simple examples, which are less helpful.
BTW, how did you solve your problem? Could you please help me, thank you so much :)

**Comment by pkombala** [comment]
not useful  not comfortable with new Django 3 or above

**Comment by JafferWilson** [comment]
Since long and no response. I guess this is waste of time for everyone. The repository owner might have abundant this repository.
I am closing this unresolved issue for everyone's good.
