### ISSUE TITLE
Ability to specify alternate paths to .js and .css files of nvd3

### ISSUE THREAD

**Issue by lgp171188** [areski/django-nvd3#34]
Currently it defaults to STATIC_URLnvd3/src/nv.d3.css, STATIC_URLd3/d3.min.js, STATIC_URLnvd3/nv.d3.min.js. I have downloaded the .js and .css files manually without using something like bower. I would like to have my CSS files in STATIC_URLcss/ and JS files in STATIC_URLjs/. So it would be great to provide choices for the path to look for these files.

**Comment by lgp171188** [comment]
@areski I have created a pull request #58 for this.

**Comment by areski** [comment]
Thanks for that, I will close this ticket and followup on the PR
