### ISSUE TITLE
python manage.py bower_install

### ISSUE THREAD

**Issue by rit2010056** [areski/django-nvd3#42]
I am trying to run this command in my project but it is not running i am running it on windows 
can anybody tell me whole step to be done

**Comment by cutreth** [comment]
Try 'python manage.py bower install' instad.

**Comment by deltaGPhys** [comment]
I also get the unknown command error, both with and without the underscore. Any fixes for this?

**Comment by goetzb** [comment]
Did you install `django-bower` as well? This is a separate package from `django-nvd3` which also needs to be installed if you want to use the management command. This management command is independent from `django-nvd3`.

To install it, simply run `pip install django-bower` in your virtual environment, as described on https://django-nvd3.readthedocs.io/en/latest/introduction.html#dependencies (for more information, please also see https://django-bower.readthedocs.io/en/latest/installation.html).
