### ISSUE TITLE
Uncaught TypeError: Cannot read property 'y' of undefined on tooltip in piechart

### ISSUE THREAD

**Issue by lgp171188** [areski/django-nvd3#45]
Using django-nvd3 version 0.7.7 this is issue is there, but not there in 0.7.4

**Comment by lgp171188** [comment]
The error is happening on the line "var y = String(graph.point.y);" of the generated JavaScript code

      chart.tooltipContent(function(key, y, e, graph) {
          var x = String(key);
              var y = String(graph.point.y);

              tooltip_str = '<center><b>'+x+'</b></center>' + y;
              return tooltip_str;
              });

**Comment by chrissmejia** [comment]
Same problem here.

**Comment by portante** [comment]
Could this be related to: https://github.com/nvd3-community/nvd3/issues/28

**Comment by lgp171188** [comment]
Can no longer see this issue on upgrading to django-nvd3 0.8.2 and modifying the code as per the demoproject django application. So closing this.

**Comment by AndreMiras** [comment]
But then why not updating the readme accordingly?
Updating chartdata in views.py with the following fixed it for me:

    extra_serie = {
        "tooltip": {"y_start": "", "y_end": " cal"},
        "color_list": color_list
    }
    chartdata = {'x': xdata, 'y1': ydata, 'extra1': extra_serie}
