### ISSUE TITLE
Datetime handling

### ISSUE THREAD

**Issue by nils-werner** [areski/django-nvd3#46]
The current way of handling date axises is very convoluted and requires a lot of boilerplate code, e.g.

    start_time = int(time.mktime(datetime.datetime(2012, 6, 1).timetuple()) * 1000)
    nb_element = 100
    xdata = range(nb_element)
    xdata = map(lambda x: start_time + x * 1000000000, xdata)

This makes it very easy to make mistakes and is very cumbersome to the user. Django itself is using `datetime.datetime` which allows much nicer handling of this kind of data.

I thing `django-nvd3` should allow the use of proper datetime data instead of asking the user to fiddle with epoch milliseconds...

**Comment by areski** [comment]
This is just for the demo project, it's only an example to show how django-nvd3 is used, but please feel free to send a PR with a better example.

**Comment by nils-werner** [comment]
Ah sorry, I was confusing this with `python-nvd3`

**Comment by areski** [comment]
Ok I will close this ticket then, go ahead and reopen if you need so
