### ISSUE TITLE
User login status can not persist

### ISSUE THREAD

**Issue by iamwucheng** [areski/django-nvd3#55]
Dear,
As the issue title says, when a user is logged in a system, when the user goes to a page which using "django-nvd3" to create a chart(line chart for example) , user log out automatically and those authenticated all lost. didn't know i am the only one who came across this problem, hope anyone can give a solution. thx:)
sorry, if i have not expressed the situation clearly. 

Best Regards.

**Comment by areski** [comment]
I dont think your problem is related to django-nvd3, you might be doing something else in your project that trigger the logout
