### ISSUE TITLE
Unable to pip install django-nvd3

### ISSUE THREAD

**Issue by marcuspen** [areski/django-nvd3#61]
Came across this today, seemed to be working fine last week...
```
(tempe2e432)Marcuss-MacBook-Pro:~ marcus$ pip install django-nvd3
Collecting django-nvd3
  Using cached django-nvd3-0.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/p4/t2_x7m896jg8w5x0lvy30nvh0000gn/T/pip-build-Bbunc2/django-nvd3/setup.py", line 10, in <module>
        with open('CHANGELOG.rst') as history_file:
    IOError: [Errno 2] No such file or directory: 'CHANGELOG.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/p4/t2_x7m896jg8w5x0lvy30nvh0000gn/T/pip-build-Bbunc2/django-nvd3
```

Seems like the CHANGELOG.rst is missing from the pypi tar.

**Comment by marcuspen** [comment]
Looked at the recent commits and it seems like you've made a change on this commit: a65b5c44
It seems to have had an effect on trying to pip install

**Comment by areski** [comment]
issue fixed by https://github.com/areski/django-nvd3/commit/139731c37666757090c2b457148307e173fbe22c

Try again I just release v0.9.1

**Comment by marcuspen** [comment]
Cheers, I'll confirm once pypi has been updated

**Comment by areski** [comment]
it s normally update immediately but I had a connection problem, now it s up https://pypi.python.org/pypi/django-nvd3/0.9.1

**Comment by marcuspen** [comment]
Working fine now :+1:

**Comment by areski** [comment]
Thanks for the report :)
