### ISSUE TITLE
Multibarchart x axis with text labels does shows NaN% in chart , but gets label correct in tooltip

### ISSUE THREAD

**Issue by pratgohi** [areski/django-nvd3#80]
Hi
First of all , Great Work by writing this wrapper it is excellent piece of work.

i have following views.py function.

def Results_View(request):
    charttype = "multiBarChart"
    buildmodel_objects=Jenkins_Build.objects.all()
    #xdata = [obj.build for obj in buildmodel_objects]
    ydata = [obj.tests_passed for obj in buildmodel_objects]
    y1data = [obj.tests_failed for obj in buildmodel_objects]

    xdata=['A','B','C','D']
    extra_serie = {"tooltip": {"y_start": " in ", "y_end": " "}}
    chartdata = { 'x': xdata,
                  'name1': 'PASSED',
                  'y1':ydata,
                  'extra1': extra_serie,
                  'extra2': extra_serie,
                  'kwargs1': {'color': '#009900'},
                  'name2': 'FAILED',
                  'y2':y1data,
                  'kwargs2': {'color': '#ff0000'}}

    chartcontainer="TEST RESULTS"
    data = {
        'charttype': charttype,
        'chartdata': chartdata,
        'chartcontainer': chartcontainer,
    }
    return render_to_response('test_results/multibarchart.html', data)

<img width="655" alt="screen shot 2016-06-10 at 7 15 40 pm" src="https://cloud.githubusercontent.com/assets/11871454/15966407/946171fa-2f40-11e6-9f77-6fbbee5519e8.png">

How to solve this NaN% problem.

Also why it takes decimal digit's for Y axis even if the number specified is in Integer? any ways to correct the same?

**Comment by pratgohi** [comment]
I have got it corrected with following solutions, I was missing the extra in template tag.

       'extra': {
            'x_is_date': False,
            'x_axis_format': '',
            'y_is_date': False,
            'y_axis_format': 'd',
            'chart_attr': {'xAxis.rotateLabels': '-90'},
            'margin_bottom' : 300,
            'reduceXTicks': False,
        }

If you think it will be helpful, i can help you add this customization examples in the demo project that will help others.

**Comment by coolankit** [comment]
Hi @pratgohi  , I'm facing same problem but your solution not working for me.
please help.
