### ISSUE TITLE
Data from database

### ISSUE THREAD

**Issue by gilleon** [areski/django-nvd3#86]
I had lek to know if there was a way of pulling data from a database(MySql) to be used for the graph instead of the static dictionary list created within views?

**Comment by areski** [comment]
you should use django ORM to connect to your DB and pull the data you need

**Comment by gilleon** [comment]
Hello Areski,

Thanks for your swift response. I am new to python for that matter django framework, if you could point me to the right direction of how to implement ORM, I will be very grateful.
