### ISSUE TITLE
Getting the error "a.dispatch.render_start is not a function"

### ISSUE THREAD

**Issue by HareeshRailCarRX** [areski/django-nvd3#91]
Is there any solution for this error?

Uncaught TypeError: a.dispatch.render_start is not a function
    at Object.a.render (core.js:91)
    at Object.a.addGraph (core.js:143)

**Comment by jamalmoir** [comment]
I am also getting this exact error.

**Comment by HareeshRailCarRX** [comment]
@areski Please help me :)

**Comment by jo-tham** [comment]
If you are still looking for a solution...

I had this error when trying to use d3 v 4.x.x.

Using d3 version 3.x.x (specifically 3.5.9 for me) resolved it.

With that, can probably close this issue @areski

**Comment by areski** [comment]
Thanks @jo-tham for commenting on this issue!
