### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by eznzel** [areski/django-nvd3#95]
I add django-nvd3 to `requirement.txt`. but Error occurred. (maybe CP949)

and try again 'pip install django-nvd3,' but same Error occurred.

![image](https://user-images.githubusercontent.com/6924383/31643032-36559cee-b329-11e7-89f3-3cf95aaf823d.png)

How can i fix this?

System infomation : windows 10 (korean)

**Comment by hackengineer** [comment]
Setting the default python encoding fixed this for a Docker install
```bash
ENV LANG C.UTF-8
...
RUN ${PYTHON} -mpip install -r requirements.txt
```

**Comment by maxtortime** [comment]
This error fixed on develop branch. You can use `pip install -e https://github.com/areski/django-nvd3.git@develop` for installing.

**Comment by areski** [comment]
New release is out so closing this ticket
just pushed a new version to Pypi: https://pypi.org/project/django-nvd3/
